### ISSUE TITLE
Paths including non-standard ASCII characters aren't recognized

### ISSUE THREAD

**Issue by Chiraii** [Arignir/Hades#14]
I am using the latest nightly release of Hades as currently available in the link given on the front-page of the repository.

While trying to load up the GBA BIOS and a game ROM, I noticed that, while the files and their respective paths existed, the emulator considered them as non-existent. Due to my Windows being set to use the French language, the paths were akin to : "C:/Téléchargements/bios.bin"

I immediately assumed that the diacritics-laden 'e' in the path name were causing an issue in recognizing the path and moved the files to the root of the disk, resulting in a path like : "C:/bios.bin". This immediately fixed the issue.

As such, I assume non-standard ASCII characters aren't properly recognized when searching for the given path to a file.

**Comment by Arignir** [comment]
Thank you for your detailed report, I will investigate this issue very soon.

**Comment by Arignir** [comment]
Hello!

The bug should be fixed now. Can you confirm everything is working as expected on your end so that I can close this issue?

Thank you so much for your time and your help!

**Comment by Chiraii** [comment]
Just tested it, no more issue with opening the ROM.

**Comment by Arignir** [comment]
Nice! Thanks =)
