### ISSUE TITLE
High CPU / GPU consumption...

### ISSUE THREAD

**Issue by IPeluchito** [Arignir/Hades#21]
CPU consumption around 40% and GPU consumption around 90% only when opening the program or in idle....

Windows 11 Build 22000.675
Intel i7 9700
Nvidia GTX 1660Ti

**Comment by Arignir** [comment]
Hello!

First of all, thank you so much for spending time playing with my emulator! It's the very first time I hear about someone using my project that isn't one of my IRL friend so it means a lot to me :D

I can confirm your issue if vsync is disabled (`Video` ->  `Enable VSync`). If this option isn't enabled, the FPS of the frontend (not the ones of the game being emulated) aren't capped, which can result in a large CPU/GPU consumption. 

With the latest release, those are now capped to 60fps if `vsync` is disabled. Can you confirm that the CPU/GPU consumption is lower now?

**Comment by IPeluchito** [comment]
Thanks to you for taking the time to work on the emulator...well here are some screenshots of how the emulator looks now:

**VSync=OFF (Default)**
![VsyncOFF](https://user-images.githubusercontent.com/64821708/193430767-782b3bef-3cba-46cf-9f05-3bab1c1a933a.png)

**Vsync=ON**
![VsyncON](https://user-images.githubusercontent.com/64821708/193430773-9ad6640b-2bc8-4610-98fa-54c008e8c0d9.png)

**Comment by Arignir** [comment]
May I ask how much hertz is your screen?

**Comment by IPeluchito** [comment]
3840x2160 / 60Hz / HDMI (video & sound) and yes, I've tested it again with today's latest modification....same results...

**Comment by Arignir** [comment]
Okay, I'll look into it again! Thanks for your feedback.

**Comment by Arignir** [comment]
Hello! Could you try again with the latest build on master? You should see major improvements :D

**Comment by IPeluchito** [comment]
Much better... although when you pause a game (Vsync=ON) the CPU consumption stays around 20% and when you remove the pause, the fps goes up to around 300 fps until after a few seconds it stabilizes at 60fps...

**Comment by Arignir** [comment]
For the CPU consumption part you're right, my condition to enable "power save mode" is that the emulation isn't started, I've pushed a fix that switches the condition to "emulation isn't started or emulation is paused", thanks! Let me know if everything is good for you so I can close the issue :D 

For the FPS counter part, yeah that's normal: FPS needs a bit of time to stabilize. The actual FPS should be stable tho, it's only the number printed that's a bit off for the first second or two.

**Comment by IPeluchito** [comment]
Now the CPU / GPU consumption are where they should be...however the emulator GUI has become slow and when removing the pause when a game is loaded the emulator takes between 12-22 seconds to stabilize its fps at 60fps... :S

**Comment by Arignir** [comment]
Bwahaha we will never see the end of this :')

On a more serious note, I think I fixed both bugs, can you please try the new version? Hopefully everything will be in order this time 🙏

**Comment by IPeluchito** [comment]
It's fixed.... :) just one last question, is it normal that when Vsync is enabled the CPU consumption is around 25% while with Vsync disabled that same consumption is around 7% ?

If it is normal, please close the issue and......Congratulations!!! xD

**Comment by Arignir** [comment]
I've seen the opposite effect (with vsync CPU is lower, and without vsync it is higher) and so far I believe it's normal and depends on your displays' refresh rate.

Thanks for your patience while resolving this issue, and thank you again for using Hades! If you find any other bug, please feel free to fill another issue 😄
