### ISSUE TITLE
[Feature Request] Remove black bars maybe ignore aspect ratio option

### ISSUE THREAD

**Issue by mrdeathjr28** [Arignir/Hades#24]
Hi

Maybe can add some option for remove black bars like ignore aspect ratio option

thanks

**Comment by Arignir** [comment]
Hello,

Yes this looks like a good idea, I'll add that soon!

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
This was adressed with commit https://github.com/Arignir/Hades/commit/e9e4aa05ff593a3a94a8e444b24cbf40ccd8f0e1.
