### ISSUE TITLE
[Feature Request] Menu option for button remaping

### ISSUE THREAD

**Issue by mrdeathjr28** [Arignir/Hades#25]
Hi

Maybe can add some option for button remaping

thanks

**Comment by Arignir** [comment]
Hello,

This is definitely in my roadmap at some point. In the mean-time, if you have the latest  version, you can already remap buttons with the configuration file. It's not as smooth and intuitive as a full UI, but it works and is already available, at least :p

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
Currently working on this issue. Here's the UI so far:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/4798413/212392973-94f4da21-308a-4d9e-a67f-4976abfe167f.png">


It's not ready yet but it should be done soon enough!

**Comment by Arignir** [comment]
Fixed with https://github.com/Arignir/Hades/pull/47. Let me know if you find any bugs!
