### ISSUE TITLE
can you use for a website?

### ISSUE THREAD

**Issue by Minemaster121** [Arignir/Hades#50]

**Comment by Arignir** [comment]
Not sure what you mean, would you like commenting more on what you expect?

**Comment by Minemaster121** [comment]
Sorry, I mean can you implement this into a website like replit or glitch?

**Comment by Arignir** [comment]
So far there's no way to use Hades on a website but that's something I'd like to do one day, hopefully!

No ETA though, it's quite far in the todo list :x
